"use client";

import { useEffect, useState } from "react";

export function TraceSummary({ traceId }: { traceId: string }) {
  const [text, setText] = useState<string | null>(null);
  const [model, setModel] = useState<string | null>(null);
  const [cached, setCached] = useState(false);

  useEffect(() => {
    let alive = true;
    fetch("/api/trace-summary", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ trace_id: traceId }),
    })
      .then((r) => r.json())
      .then((d) => {
        if (!alive) return;
        setText(d.summary ?? d.error ?? null);
        setModel(d.model ?? null);
        setCached(!!d.cached);
      })
      .catch(() => alive && setText(null));
    return () => {
      alive = false;
    };
  }, [traceId]);

  return (
    <div className="mb-6">
      <div className="eyebrow mb-2">Plain-English summary</div>
      {text === null ? (
        <div
          className="h-5 w-2/3 rounded animate-pulse"
          style={{ background: 'oklch(0.92 0.006 40 / 0.7)' }}
        />
      ) : (
        <p className="text-[15px] text-ink-800 leading-[1.6] max-w-[780px]">
          {text}
        </p>
      )}
      {model && model !== "deterministic" && (
        <div className="text-[10.5px] text-ink-400 mt-2">
          Generated by {model}
          {cached ? " · cached" : ""}
        </div>
      )}
    </div>
  );
}
